### ISSUE TITLE
Read RoadNetwork from .net.xml

### ISSUE THREAD

**Issue by Maxic** [baumfalk/TrafficMAS#3]
The road network should be read from the .net file generated by NETCONVERT. This solves two issues:
- The internal roads which SUMO uses for junctions are included in the network and won't cause problems
- SUMO does not need the .nod .con and .edg files, so they might not always be available. Therefore our application should not need them either.

**Comment by baumfalk** [comment]
We generate a .netfile with `netconvert -c file.netccfg`
If we don't have the option `no-internal-links`, netconvert will generate internal links to connect edges in a natural way (i.e. no visual teleports). This will give an error when we try to update the current road, because our framework doesn't know of these internal links.

We have three options
- ignore internal links, i.e. don't let an agent do anything when it is on an internal edge (one that isn't in the road network). A problem with this is that it increases the dependence on sumo, since other simulations might not have this.
- also load the internal links in the road network of the framework. This has as an additional problem that we need to think about how we include those internal links in routes.
- disallow internal links, so only run netconvert with `netconvert -c file.netccfg -no-internal-links`. The downside of this is that it looks weird in sumo-gui.

**Comment by baumfalk** [comment]
I went for an bit of changed version of option 1, which is also robust for different implementations. If an agent arrives on an internal link, its road will be updated to null, since the internal road is not known to the framework. Agents with a road that is null don't perform an action.
